### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by angwandi** [NikitaMasev/flutter_ticket_material#3]
Is there a way to flip the left and right widgets to the top and bottom instead?

**Comment by NikitaMasev** [comment]
@angwandi Hi! No, the original design it was planned exactly as it is now. If we change the layout so much, then this is, in principle, a different widget or plugin.

**Comment by angwandi** [comment]
@NikitaMasev okay, no problem. I will fork this and see how i can modify it. I think it's just question of modifying the row to a column. Thanks
